spring.application.name=skulin

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/skulin}
spring.datasource.username=${DATABASE_USERNAME:neondb_owner}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.check-template-location=false
spring.thymeleaf.cache=false